# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Update packages with $ pre-commit autoupdate
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^docs/_images/  # don't touch svg files
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: mixed-line-ending
        args: ['--fix=lf']
-   repo: https://github.com/ikamensh/flynt/
    rev: '0.78'
    hooks:
    -   id: flynt
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
    -   id: pyupgrade
        args: ['--py37-plus']
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black>=21.9b0]
-   repo: https://github.com/pycqa/flake8
    rev: '6.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-colors, flake8-bugbear, flake8-comprehensions]
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle
        files: ^src/billiards/
        additional_dependencies: ["tomli"]  # config in pyproject.toml file
-   repo: https://github.com/pycqa/doc8
    rev: v1.1.1
    hooks:
    -   id: doc8
        files: ^docs/
